const LogActions = {
  //  Seguridad
  LOGIN_EXITOSO: "LOGIN_EXITOSO",
  LOGIN_FALLIDO: "LOGIN_FALLIDO",
  LOGOUT: "LOGOUT",
  PASSWORD_RESET: "PASSWORD_RESET",

  //  Transacciones
  TRANSFERENCIA_REALIZADA: "TRANSFERENCIA_REALIZADA",
  TRANSFERENCIA_FALLIDA: "TRANSFERENCIA_FALLIDA",
  DEPOSITO_REALIZADO: "DEPOSITO_REALIZADO",
  RETIRO_REALIZADO: "RETIRO_REALIZADO",

  //clientes
  CLIENTE_CREADO: "CLIENTE_CREADO",
  CLIENTE_ELIMINADO: "CLIENTE_ELIMINADO",
  CLIENTE_ACTUALIZADO: "CLIENTE_ACTUALIZADO",
  


  //  Créditos
  CREDITO_ASIGNADO: "CREDITO_ASIGNADO",
  SOLICITUD_CREDITO: "SOLICITUD_CREDITO",
  PAGO_CREDITO: "PAGO_CREDITO",
  CREDITO_RECHAZADO: "CREDITO_RECHAZADO",
  ERROR_CREDITO_CREAR: "ERROR_CREDITO_CREAR",

  //  Usuarios
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  BLOCK_USER: "BLOCK_USER",
  DELETE_USER: "DELETE_USER",
  REGISTER_USER: "USER_REGISTER",
  REGISTER_FAILED: "REGISTER_FAILED",


  //  Cuentas
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  BLOCK_ACCOUNT: "BLOCK_ACCOUNT",
  CLOSE_ACCOUNT: "CLOSE_ACCOUNT",

  

  //  Tarjetas
  CREATE_CARD: "CREATE_CARD",
  BLOCK_CARD: "BLOCK_CARD",
  UNBLOCK_CARD: "UNBLOCK_CARD",
  REPORT_CARD: "REPORT_CARD",
  DELETE_CARD: "DELETE_CARD",
  

  //  Tickets
  CREATE_TICKET: "CREATE_TICKET",
  CLOSE_TICKET: "CLOSE_TICKET",
  TICKET_FAILED_CREATE: "TICKET_FAILED_CREATE",

};

module.exports = LogActions;